import java.util.Random;

/**
 * The class PlayingField implements the {@link PlayingField} of the memory game
 * as a two-dimensional array.
 * In addition, a controlArray of the boolean type is created to store
 * whether a card is revealed or not.
 */
public class PlayingField {

    /**
     * Height and Width of the {@link PlayingField}
     * TODO This values are only for the Prototype, later the
     *  values are generated by selecting the size of the {@link PlayingField}
     */
    private final int height = 4;
    private final int width = 4;

    /**
     * Array of the {@link PlayingField}
     */
    private Card[][] board;


    /**
     * The Constructor creates a new {@link PlayingField} and fills the board with {@link Card}
     */
    public PlayingField() {
        board = new Card[height][width];
        fillWithCards();
    }

    /**
     * @return the {@code board}
     */
    public Card[][] getBoard() {
        return board;
    }

    /**
     * Getter of the playingfields {@code height}
     *
     * @return the {@code height}
     */
    public int getHeight() {
        return height;
    }


    /**
     * Getter of the playingfields {@code width}
     *
     * @return the {@code width}
     */
    public int getWidth() {
        return width;
    }

/**
 * TODO Setter of height and width should be implemented
 *  in this Iteration they are redundant, because they are final.
 */


    /**
     * Checks whether all cards have already been turned over.
     * If true, then the images of all cards are open.
     * If false, at least one image is still hidden.
     *
     * @return whether all cards are open or not.
     */
    public boolean areAllCardsOpen() {
        for (int row = 0; row < height; ++row) {
            for (int col = 0; col < width; ++col) {
                if (!(getCard(row, col).isRevealed())) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Returns a specified card.
     *
     * @param row Row position of the selected card
     * @param col Column position of the selected card
     * @return the selected card
     */
    public Card getCard(int row, int col) {
        return board[row][col];
    }

    /**
     * Removes a {@link Card} pair from the {@code board}.
     *
     * @param row1 Row position of the first selected card
     * @param col1 Column position of the first selected car
     * @param row2 Row position of the second selected card
     * @param col2 Column position of the second selected car
     */
    public void removeCards(int row1, int col1, int row2, int col2) {
        board[row1][col1] = null;
        board[row2][col2] = null;
        getCard(row1,col1).setRevealed(true);
        getCard(row2,col2).setRevealed(true);
    }

    /**
     * Reveals a {@link Card} identified by row and column.
     *
     * @param row of the desired card
     * @param col of the desired card
     * @return the {@code value} of a card
     */
    public CardValue revealCard(int row, int col) {
        if(!getCard(row,col).isRevealed()) {
            System.err.println("Error: Card is already revealed");
            return null;
        } else {
            return getCard(row, col).getValue();
        }
    }

    /**
     * Reveals the first selected {@link Card} of a turn
     *
     * @param firstRow of the {@link Card}
     * @param firstCol of the {@link Card}
     * @param controller is needed because of the interaction between view and model
     * @return the image of the first {@link Card} as Integer.
     */
    public int revealFirstCard(int firstRow, int firstCol, Controller controller) {
         controller.setTurnStatus(TurnStatus.ACTIVTURN);
         Card firstCard = getCard(firstRow, firstCol);
         firstCard.setRevealed(true);
         int firstCardImage = firstCard.visualizeCard(revealCard(firstRow, firstCol));
         return firstCardImage;
    }


    /**
     * Reveals the second selected {@link Card} of a turn.
     * This method is needed, because additionally information has to be proofed
     *
     * @param secondRow of the {@link Card}
     * @param secondCol of the {@link Card}
     * @param controller is needed because of the interaction between view and model
     * @return the image of the second {@link Card} as Integer
     */
    public int revealSecondCard(int secondRow, int secondCol, Controller controller) {
        if(!getCard(secondRow, secondCol).isRevealed()) {
            System.err.println("Error: Card is already revealed");
            return 0;
        } else {
            controller.setTurnStatus(TurnStatus.NOTSTARTED);
            Card secondCard = getCard(secondRow, secondCol);
            int secondCardImage = secondCard.visualizeCard(revealCard(secondRow, secondCol));
            return secondCardImage;
        }
    }

    /**
     * Checks weather two selected {@link Card} have the same image and therefore form a pair
     *
     * @param rowFirstCard : Row of the first {@link Card}
     * @param colFirstCard : Column of the first {@link Card}
     * @param rowSecondCard : Row of the second {@link Card}
     * @param colSecondCard : Column of the second {@link Card}
     * @param controller is needed because of the interaction between view and model
     */
    public void pairCheck(int rowFirstCard, int colFirstCard, int rowSecondCard, int colSecondCard, Controller controller){
        Card firstCard = getCard(rowFirstCard, colFirstCard);
        Card secondCard = getCard(rowSecondCard, colSecondCard);

         if (firstCard.getValue().equals(secondCard.getValue())) {
             System.out.println("You've found a pair!");
             removeCards(rowFirstCard, colFirstCard, rowSecondCard, colSecondCard);
             if (areAllCardsOpen()) {
                controller.setGameStatus(GameStatus.END);
                System.out.println("You won!");
             }
         } else {
             getCard(rowFirstCard, colFirstCard).setRevealed(false);
         }
    }

    /**
     * Fills the {@code board} with {@link Card} elements.
     * TODO This method must be changed in later iterations - Jan
     */
    private void fillWithCards() {
        //New pairs of cards are created
        Card card1 = new Card(CardValue.ONE);
        Card card2 = new Card(CardValue.TWO);
        Card card3 = new Card(CardValue.THREE);
        Card card4 = new Card(CardValue.FOUR);
        Card card5 = new Card(CardValue.FIVE);
        Card card6 = new Card(CardValue.SIX);
        Card card7 = new Card(CardValue.SEVEN);
        Card card8 = new Card(CardValue.EIGHT);
        //All cards are saved in board
        board[0][0] = card1;
        board[0][1] = card1;
        board[0][2] = card2;
        board[0][3] = card2;
        board[1][0] = card3;
        board[1][1] = card3;
        board[1][2] = card4;
        board[1][3] = card4;
        board[2][0] = card5;
        board[2][1] = card5;
        board[2][2] = card6;
        board[2][3] = card6;
        board[3][0] = card7;
        board[3][1] = card7;
        board[3][2] = card8;
        board[3][3] = card8;
        //Board is shuffled
        shuffleBoard();
    }

    /**
     * Shuffles {@link Card} elements of {@code board}.
     */
    private void shuffleBoard() {
        Card tmp;
        int randRow, randCol;
        Random r = new Random();
        for (int i = 0; i < board.length; i++) {
            for (int j = 0; j < board[i].length; j++) {
                randRow = r.nextInt(board.length - 1);
                randCol = r.nextInt(board.length - 1);
                tmp = board[i][j];
                board[i][j] = board[randRow][randCol];
                board[randRow][randCol] = tmp;
            }
        }
    }
}